apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-app
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: polling-app
  template:
    metadata:
      labels:
        app: polling-app
    spec:
      containers:
        - name: polling-app
          image: suyashrajesh/polling-app:prod
          ports:
            - containerPort: 8080
