apiVersion: v1
kind: Service
metadata:
  name: polling-app-service
  namespace: prod
spec:
  selector:
    app: polling-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
