apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polling-app
  template:
    metadata:
      labels:
        app: polling-app
    spec:
      containers:
        - name: polling-app
          image: suyashrajesh/polling-app:dev   # Use your DockerHub image name
          ports:
            - containerPort: 8080
